[vars]
brewfiles_dir = "{{ config_root }}/brewfiles"

[task_templates."brewfile:bundle_install"]
description = "Run mise command:brew:bundle for a brewfile"
run = 'brew bundle --file="{{ vars.brewfiles_dir }}/{{ vars.brewfile }}"'

[tasks."install:terminal"]
description = "Install terminal Brewfiles for the current environment"
run = [
  # brew can only run serially
  { task = "install:terminal:required" },
  { task = "install:terminal:common" },
  { task = "install:terminal:for_env" },
]

[tasks."install:terminal:required"]
description = "Install the required terminal Brewfile"
extends = "brewfile:bundle_install"
vars = { brewfile = "terminal.required" }

[tasks."install:terminal:common"]
description = "Install the common terminal Brewfile"
extends = "brewfile:bundle_install"
vars = { brewfile = "terminal.common" }

[tasks."install:gui"]
description = "Install GUI Brewfiles for the current environment"
run = [{ task = "install:gui:common" }, { task = "install:gui:for_env" }]

[tasks."install:gui:common"]
description = "Install the common GUI Brewfile"
extends = "brewfile:bundle_install"
vars = { brewfile = "gui.common" }
