source ~/.vim/base.vim
source ~/.vim/mappings.vim
source ~/.vim/plugins.vim
source ~/.vim/colors.vim

if has('nvim')
  source ~/.vim/nvim.vim
end

if filereadable(expand("~/.vimrc.local"))
  source ~/.vimrc.local
endif

