return {}
-- return {
--   -- If you use neotest, give its floats a nicer border
--   {
--     "nvim-neotest/neotest",
--     optional = true,
--     opts = function(_, opts)
--       opts = opts or {}
--       opts.floating = vim.tbl_deep_extend("force", opts.floating or {}, { border = "rounded" })
--       return opts
--     end,
--   },
--
--   -- All UI highlight/link tweaks live here: floats, pickers, neotest panes
--   {
--     "LazyVim/LazyVim",
--     init = function()
--       -----------------------------------------------------------------------
--       -- 1) Float/border defaults (play nice with NeoSolarized)
--       -----------------------------------------------------------------------
--       local aug = vim.api.nvim_create_augroup("neo_ui_highlights", { clear = true })
--       local function set_global_float_links()
--         -- consistent float look everywhere
--         vim.api.nvim_set_hl(0, "NormalFloat", { link = "Pmenu" })
--         vim.api.nvim_set_hl(0, "FloatBorder", { link = "WinSeparator" })
--         vim.api.nvim_set_hl(0, "FloatTitle", { link = "Title" })
--       end
--
--       -----------------------------------------------------------------------
--       -- 2) Picker highlights (Snacks default; Telescope/fzf-lua if enabled)
--       -----------------------------------------------------------------------
--       local function set_picker_hls()
--         local function link(g, target)
--           vim.api.nvim_set_hl(0, g, { link = target, default = false })
--         end
--
--         -- Snacks (unchanged except selection -> PmenuSel)
--         link("SnacksPicker", "NormalFloat")
--         link("SnacksPickerList", "NormalFloat")
--         link("SnacksPickerPreview", "NormalFloat")
--         link("SnacksPickerPrompt", "Pmenu")
--         link("SnacksPickerMatch", "Search")
--         link("SnacksPickerBorder", "FloatBorder")
--         link("SnacksPickerPreviewBorder", "FloatBorder")
--         link("SnacksPickerTitle", "FloatTitle")
--         link("SnacksPickerPreviewTitle", "FloatTitle")
--         link("SnacksPickerPromptTitle", "FloatTitle")
--         for _, g in ipairs({
--           "SnacksPickerListCursorLine",
--           "SnacksPickerCursorLine",
--           "SnacksPickerPreviewCursorLine",
--         }) do
--           link(g, "PmenuSel")
--         end
--
--         -- Telescope
--         link("TelescopeSelection", "PmenuSel") -- selected row
--         link("TelescopeSelectionCaret", "PmenuSel")
--         link("TelescopeMultiSelection", "PmenuSel")
--         link("TelescopeMatching", "Search")
--         link("TelescopePromptNormal", "NormalFloat")
--         link("TelescopeResultsNormal", "NormalFloat")
--         link("TelescopePreviewNormal", "NormalFloat")
--         link("TelescopePromptBorder", "FloatBorder")
--         link("TelescopeResultsBorder", "FloatBorder")
--         link("TelescopePreviewBorder", "FloatBorder")
--         link("TelescopePromptTitle", "FloatTitle")
--         link("TelescopeResultsTitle", "FloatTitle")
--         link("TelescopePreviewTitle", "FloatTitle")
--
--         -- fzf-lua
--         link("FzfLuaNormal", "NormalFloat")
--         link("FzfLuaBorder", "FloatBorder")
--         link("FzfLuaTitle", "FloatTitle")
--         link("FzfLuaCursorLine", "PmenuSel") -- selected row
--         link("FzfLuaPreviewCursorLine", "PmenuSel")
--         link("FzfLuaCursor", "PmenuSel") -- caret/arrow
--         link("FzfLuaSearch", "Search")
--       end
--
--       -- Apply on theme load + once at startup
--       vim.api.nvim_create_autocmd("ColorScheme", {
--         group = aug,
--         callback = function()
--           set_global_float_links()
--           set_picker_hls()
--         end,
--       })
--       set_global_float_links()
--       set_picker_hls()
--
--       -----------------------------------------------------------------------
--       -- 3) Neotest windows: distinct bg + clearer border, window-local only
--       -----------------------------------------------------------------------
--       local grp = vim.api.nvim_create_augroup("neotest_contrast_bg", { clear = true })
--
--       local function set_winhl_for_neotest(win)
--         -- use themed groups (no hex): Pmenu bg, PmenuSel cursorline, Title border
--         local map = {
--           "Normal:Pmenu",
--           "NormalNC:Pmenu",
--           "NormalFloat:Pmenu",
--           "CursorLine:PmenuSel",
--           "FloatTitle:Title",
--           "FloatBorder:Title",
--         }
--         local joined = table.concat(map, ",")
--         local cur = vim.wo[win].winhl
--         vim.wo[win].winhl = (cur ~= "" and (cur .. ",") or "") .. joined
--       end
--
--       local neotest_fts = {
--         "neotest-summary",
--         "neotest-output",
--         "neotest-output-panel",
--         "neotest-attach",
--       }
--
--       vim.api.nvim_create_autocmd({ "FileType", "BufWinEnter" }, {
--         group = grp,
--         callback = function(ev)
--           local ft = vim.bo[ev.buf].filetype
--           for _, want in ipairs(neotest_fts) do
--             if ft == want then
--               set_winhl_for_neotest(0)
--               -- tidy UI defaults in these panels
--               vim.opt_local.number = false
--               vim.opt_local.relativenumber = false
--               vim.opt_local.signcolumn = "no"
--               vim.opt_local.cursorline = true
--               break
--             end
--           end
--         end,
--       })
--     end,
--   },
-- }
