[tools]
node = { version = "lts" }
"npm:@mermaid-js/mermaid-cli" = "latest"
pipx = "latest"
pnpm = "latest"
uv = "latest"
python = "3.12"
1password-cli = "latest"

[settings]
experimental = true
npm.package_manager = "pnpm"
python.uv_venv_auto = "create|source"

[hooks]
postinstall = '''
if printf '%s\n' "${MISE_INSTALLED_TOOLS:-}" | grep -q '^python@'; then
  mise run nvim:python:rebuild
fi
'''

[env]
# UV_PYTHON = { value = "{{ tools.python.path }}", tools = true }
nvim_virtualenv = "{{xdg_cache_home}}/venvs/nvim"
