[tools]
node = { version = "lts" }
rust = "stable"
cargo-binstall = "latest"
go = "latest"
bun = "latest"
"npm:@github/copilot" = "latest"

[settings]
npm.package_manager = "bun"

[tasks."update:for_env"]
description = "Update tools for environment: personal"
run = ["npm i -g @openai/codex"]
