# Tools and packages for the work profile with the workstation feature.
# TODO: Conslidate into just "work"
[tools]
actionlint = "latest"
coursier = "latest"
k9s = "latest"
powershell = "latest"
task = "latest"
zizmor = "latest"
"pipx:sqlfluff" = "latest"
"pipx:azure-cli" = "latest"
"github:git-ecosystem/git-credential-manager" = "latest"

[bootstrap.packages]
"brew:docker" = { os = ["linux", "macos"] }
"brew:docker-compose" = { os = ["linux", "macos"] }
"brew:docker-credential-helper" = { os = ["linux", "macos"] }
"brew:libpq" = { os = ["linux", "macos"] }
"brew:postgresql@18" = { os = ["linux", "macos"] }
"pacman:docker" = "latest"
"pacman:docker-compose" = "latest"
"pacman:docker-credential-pass" = "latest"
"pacman:postgresql" = "latest"
"pacman:postgresql-libs" = "latest"

[tasks."bootstrap:work-workstation"]
description = "Install the Azure Bicep CLI for a work workstation"
run = "az bicep install"

[settings]
minimum_release_age_excludes = ["pipx:azure-cli", "pipx:sqlfluff"]
