[tools]
node = { version = "lts" }
rust = "stable"
cargo-binstall = "latest"
go = "latest"
bun = "latest"
"npm:@github/copilot" = "latest"

[settings]
npm.package_manager = "bun"

[tasks."update:for_env"]
description = "Update tools for environment: personal"
run = ["npm i -g @openai/codex"]

[tasks."install:terminal:for_env"]
description = "Install the personal terminal Brewfile"
extends = "brewfile:bundle_install"
vars = { brewfile = "terminal.env.personal" }

[tasks."install:gui:for_env"]
description = "Install the personal GUI Brewfile"
extends = "brewfile:bundle_install"
vars = { brewfile = "gui.env.personal" }
